name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: do stuff
        run: |
          sudo apt-get update
          sudo apt-get install -y neofetch inxi
          whoami
          sudo whoami
          sudo neofetch
          sudo inxi -Fzxa
          
